import {one,run,secret,now} from './db';import {ApiError,text} from './validation';import {hash} from './security';import {ResendClient,type EmailPayload} from './integrations/resend';
type Subscriber={id:string;email:string;status:string;token_hash:string;confirm_expires_at:number;email_payload:string;email_status:string;created_at:string};
export function newsletterConfig(){const privacy=secret('NEWSLETTER_PRIVACY_TEXT'),version=secret('NEWSLETTER_PRIVACY_VERSION');return {enabled:secret('NEWSLETTER_PRIVACY_APPROVED')==='true'&&!!privacy&&!!version&&!!secret('NEWSLETTER_FROM')&&secret('RESEND_API_KEY').startsWith('re_')&&secret('NEWSLETTER_TOKEN_SECRET').length>=32&&/^https:\/\//.test(secret('SITE_ORIGIN')),privacy,version};}
async function signed(id:string,purpose:string,expires:number){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret('NEWSLETTER_TOKEN_SECRET')),{name:'HMAC',hash:'SHA-256'},false,['sign']);const message=`${id}.${purpose}.${expires}`;const bytes=new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(message)));return message+'.'+Array.from(bytes).map(b=>b.toString(16).padStart(2,'0')).join('');}
async function verify(token:string,purpose:string){if(secret('NEWSLETTER_TOKEN_SECRET').length<32)throw new ApiError(503,'El servicio de suscripciones no está configurado.');const parts=token.split('.');if(parts.length!==4||parts[1]!==purpose||!/^\d+$/.test(parts[2]))throw new ApiError(400,'Enlace no válido.');const expected=await signed(parts[0],purpose,Number(parts[2]));if(await hash(expected)!==await hash(token))throw new ApiError(400,'Enlace no válido.');return {id:parts[0],expires:Number(parts[2])};}
export async function subscribe(emailInput:unknown,consent:unknown,version:unknown){const config=newsletterConfig();if(!config.enabled)throw new ApiError(503,'Las suscripciones todavía no están habilitadas.');if(consent!==true||version!==config.version)throw new ApiError(400,'Confirma tu consentimiento con el aviso vigente.');const email=text(emailInput,'el correo',254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new ApiError(400,'Revisa tu correo electrónico.');let row=await one<Subscriber>('SELECT * FROM subscribers WHERE email=?',email);if(row?.status==='active')return {ok:true};if(row?.status==='unsubscribed')throw new ApiError(409,'Esta dirección fue dada de baja. Contacta con la librería para reactivar tu suscripción.');
 if(!row){const id=crypto.randomUUID(),expires=Date.now()+7*86400000,token=await signed(id,'confirm',expires),origin=secret('SITE_ORIGIN');const payload:EmailPayload={from:secret('NEWSLETTER_FROM'),to:[email],subject:'Confirma tu suscripción a El Diván',text:`Solicitaste recibir novedades de El Diván Mundo Psicoanalítico.\n\nConfirma tu suscripción aquí:\n${origin}/newsletter/confirmar#token=${encodeURIComponent(token)}\n\nSi no hiciste esta solicitud, ignora este mensaje. No te suscribiremos sin confirmación.`};await run("INSERT INTO subscribers(id,email,status,token_hash,consent_version,confirm_expires_at,email_payload,email_status,created_at) VALUES(?,?,'pending',?,?,?,?,'pending',?) ON CONFLICT(email) DO NOTHING",id,email,await hash(token),config.version,expires,JSON.stringify(payload),now());row=await one<Subscriber>('SELECT * FROM subscribers WHERE email=?',email);}
 if(!row)throw new ApiError(500,'No pudimos guardar tu solicitud.');if(row.email_status==='sent')return {ok:true};if(Date.now()-Date.parse(row.created_at)>23*3600000)throw new ApiError(409,'La confirmación requiere revisión de la librería.');try{await new ResendClient(secret('RESEND_API_KEY')).send(JSON.parse(row.email_payload),'divan-newsletter-confirm/'+row.id);await run("UPDATE subscribers SET email_status='sent' WHERE id=?",row.id);}catch{throw new ApiError(502,'No pudimos enviar la confirmación. Puedes intentarlo nuevamente.');}return {ok:true};}
export async function confirmSubscription(tokenInput:unknown){const token=text(tokenInput,'el enlace',500),v=await verify(token,'confirm');if(v.expires<Date.now())throw new ApiError(410,'El enlace de confirmación caducó.');const row=await one<Subscriber>('SELECT * FROM subscribers WHERE id=?',v.id);if(!row||row.token_hash!==await hash(token))throw new ApiError(400,'Enlace no válido.');if(row.status==='unsubscribed')throw new ApiError(409,'La suscripción fue dada de baja.');await run("UPDATE subscribers SET status='active' WHERE id=? AND status='pending'",v.id);return {ok:true,unsubscribeToken:await signed(v.id,'unsubscribe',0)};}
export async function unsubscribe(tokenInput:unknown){const v=await verify(text(tokenInput,'el enlace',500),'unsubscribe');await run("UPDATE subscribers SET status='unsubscribed' WHERE id=?",v.id);return {ok:true};}
export async function unsubscribeLink(id:string){return secret('SITE_ORIGIN')+'/newsletter/baja#token='+encodeURIComponent(await signed(id,'unsubscribe',0));}
