import { one,run,secret,now } from './db';
import { ApiError } from './validation';
export async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('');}
export function cookie(request:Request,name:string){return request.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='))?.slice(name.length+1)||'';}
export function sessionCookie(request:Request,name:string,value:string,age:number){return `${name}=${value}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${age}${new URL(request.url).protocol==='https:'?'; Secure':''}`;}
export async function isAdmin(request:Request){const token=cookie(request,'divan_admin');if(!token)return false;const session=await one('SELECT role FROM sessions WHERE hash = ? AND expires_at > ?',await hash(token),Date.now());return session?.role==='admin';}
export async function requireAdmin(request:Request){if(!await isAdmin(request))throw new ApiError(401,'Inicia sesión como administrador.');}
export async function limit(request:Request,scope:string,max=10){const ip=request.headers.get('cf-connecting-ip')||'local';const key=scope+':'+await hash(ip);const expiry=Date.now()+900000;await run('INSERT INTO rate_limits (key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires_at < ? THEN 1 ELSE count+1 END,expires_at=CASE WHEN expires_at < ? THEN ? ELSE expires_at END',key,expiry,Date.now(),Date.now(),expiry);const r=await one<{count:number}>('SELECT count FROM rate_limits WHERE key=?',key);if((r?.count||0)>max)throw new ApiError(429,'Demasiados intentos. Espera unos minutos.');}
export async function checkAdminPassword(password:string){const expected=secret('ADMIN_PASSWORD_SHA256');if(!expected||!/^[a-f0-9]{64}$/.test(expected))throw new ApiError(503,'El acceso administrativo aún no está configurado.');const actual=await hash(password);let different=0;for(let i=0;i<64;i++)different|=expected.charCodeAt(i)^actual.charCodeAt(i);return different===0;}
export async function audit(action:string,entity:string){await run('INSERT INTO audit (id,actor,action,entity,created_at) VALUES (?,?,?,?,?)',crypto.randomUUID(),'admin',action,entity,now());}
